mode: "test"

data_dir: "../dataset/nyud2"

task:
  attribute:
    num_classes: 2
    category: ["Wood", "Painted", "Paper", "Glass", "Brick", "Metal", "Flat", "Plastic", "Textured", "Glossy", "Shiny"]
  affordance:
    num_classes: 2
    category: ["L", "M", "R", "S", "W"]
  segmentation:
    num_classes: 40
    category: ["Segmentation"]

data_mean: [0.29010095242892997, 0.32808144844279574, 0.28696394422942517]
data_std: [0.1829540508368939, 0.18656561047509476, 0.18447508988480435]
ms_scales: [0.9, 1, 1.25]
save_vis: true
have_gt: true

workers: 10
batch_size: 1

save_dir: "output"

resume: ""
