mode: "train"

data_dir: "../dataset/umd/novel"

affordance:
  ["grasp", "cut", "scoop", "contain", "pound", "support", "wrap-grasp"]
num_objects: 17

crf:
  kernels_radius: 5
  kernels_desc:
    -
      weight: 1
      xy: 20
      image: 0.01

dataset_mean: [91.0225, 88.7460, 98.6912]
dataset_std: [39.2350, 35.3153, 25.9143]

epochs: 100
batch_size: 4
workers: 10

lr: 0.001
momentum: 0.9
weight_decay: 0.0001

save_dir: "output"

resume: ""
restart: false
