mode: "train"

data_dir: "../dataset/umd/category"

affordance:
  ["grasp", "cut", "scoop", "contain", "pound", "support", "wrap-grasp"]

dataset_mean:
dataset_std:

epochs: 100
batch_size: 4
workers: 10

lr: 0.001
momentum: 0.9
weight_decay: 0.0001

save_dir: "output"

resume: "ignore_archive/object/hc_refine/model/checkpoint_latest.pth"
restart: true
