mode: "train"

train_level: "weak_online" # dense, weak_online, weak_offline

data_dir: "../dataset/cad120/object"

affordance:
  ["openable", "cuttable", "pourable", "containable", "supportable", "holdable"]

stroke_diameter: 30
use_grabcut: False

random_crop_size: [321, 321] # [width, height]
random_scale_max: 2.0
random_scale_min: 1.0
random_tilt_max_deg: 10
random_wiggle_max_ratio: 0
random_horizon_reflect: True

dataset_mean: [132.47758920907586, 106.32022472065732, 111.5704799224029]
dataset_std: [67.45043019809088, 70.23484330785524, 72.19806953380163]

epochs: 100
batch_size: 4
workers: 10

lr: 0.007
momentum: 0.9
weight_decay: 0.0001

save_dir: "output"

resume: ""
