mode: "train"

train_level: "weak_online" # dense, weak_online, weak_offline

data_dir: "../dataset/cad120/object"

affordance:
  ["openable", "cuttable", "pourable", "containable", "supportable", "holdable"]
class_weight: [0.22723687, 0.54991320, 0.07481813, 0.05361520, 0.05946079, 0.03495581]

update_dataset: False
use_grabcut: False

stroke_diameter: 40
random_crop_size: [321, 321] # [width, height]
random_scale_max: 1.25
random_scale_min: 0.8
random_tilt_max_deg: 10
random_wiggle_max_ratio: 0
random_horizon_reflect: True

dataset_mean: [132.47758921, 106.32022472, 111.57047992]
dataset_std: [67.45043020, 70.23484331, 72.19806953]

epochs: 100
batch_size: 4
workers: 10

lr: 0.001
momentum: 0.9
weight_decay: 0.0001

save_dir: "output"

resume: ""
