mode: "train"

data_dir: "../dataset/cad120/actor"

affordance:
  ["openable", "cuttable", "pourable", "containable", "supportable", "holdable"]
num_objects: 12

crf:
  weight: 0.1
  kernels_radius: 5
  kernels_desc:
    -
      weight: 1
      xy: 20
      image: 0.1

dataset_mean: [136.5133, 108.5417, 113.0168]
dataset_std: [67.4025, 70.7446, 72.1553]

epochs: 100
batch_size: 4
workers: 10

lr: 0.001
momentum: 0.9
weight_decay: 0.0001

save_dir: "output"

resume: "ignore_archive/actor/hc_refine/model/checkpoint_latest.pth"
restart: true
