mode: "train"

data_dir: "../dataset/cad120/object"

affordance:
  ["openable", "cuttable", "pourable", "containable", "supportable", "holdable"]
class_weight: [0.22348881, 0.43797258, 0.09598596, 0.08307076, 0.08343790, 0.07604400]

random_crop_size: [320, 320] # [width, height]
random_scale_max: 2
random_scale_min: 0.5
random_tilt_max_deg: 10
random_wiggle_max_ratio: 0
random_horizon_reflect: True

dataset_mean: [132.47758921, 106.32022472, 111.57047992]
dataset_std: [67.45043020, 70.23484331, 72.19806953]

epochs: 100
batch_size: 4
workers: 10

lr: 0.007
momentum: 0.9
weight_decay: 0.0001

save_dir: "output"

resume: ""
